import { defineType,defineField } from "sanity"
export const startup=defineType({
    name:'startup',
    title:'StartUp',
    type:'document',
    fields:[
        defineField({
            name:'title',
            type:'string'
        }),
         defineField({
            name:'slug',
            type:'slug',
            options:{
                source:'title'   //here this means the slug which is a URL-friendly will be autogenerated by sanity depending upon the title of slug
            }
        }),
         defineField({
            name:'author',
            type:'reference',
            to:{type:'author'}   //this helps us to make a startups by specific author.
        }),
        defineField({
            name:'views',
            type:'number'
        }),
          defineField({
            name:'description',
            type:'text'
        }),
          defineField({
            name:'category',
            type:'string',
            validation:(Rule)=>Rule.min(1).max(20).required().error('Please enter a category.')   //here its telling the min character must be 1 and the maximum character must be 20.
        })
        ,
         defineField({
            name:'image',
            type:'url',
            validation:(Rule)=>Rule.required()
        }),
         defineField({
            name:'pitch',
            type:'markdown',  //and this filed provides us the markddown field with properties like bold text , underline and so on.

        })


    ]

}) 